[package]
name = "parallelos"
version = "1.0.0"
edition = "2024"

[lib]
name = "parallelos"
path = "src/lib.rs"

[[bench]]
name = "bench"
path = "bench/bench.rs"
harness = false

[dependencies]
crossbeam = "0.8.5"
fastrand = "2.5.0"
anyhow = "1.0.104"

[dev-dependencies]
sha2 = "0.11.0"
hex = "0.4.3"
aes-gcm = "0.11.1"
zstd = "0.14.0"
# core_affinity = "0.8.3"
# plotters = "0.3.7"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
incremental = false
debug = false

[profile.dev]
opt-level = 1
incremental = true
debug = "full"
